mysticcraft:
  integrations:
    itemsadder:
      enabled: true

  messages:
    put_take: 'OFF'   # CHAT | ACTION_BAR | OFF

  protections:
    enabled: true
    require_permission: false
    block:
      pistons: true
      explosions: true
      fluids: true
      armorstand_direct: true

  effects:
    enabled: true
    assemble:
      particle: ENCHANTMENT_TABLE
      count: 60
      offset: 0.50
      speed: 0.01
      sound: BLOCK_ENCHANTMENT_TABLE_USE
      volume: 1.0
      pitch: 1.2
    disassemble:
      particle: CLOUD
      count: 40
      offset: 0.40
      speed: 0.00
      sound: BLOCK_GLASS_BREAK
      volume: 0.9
      pitch: 1.0
    put:
      particle: END_ROD
      count: 12
      offset: 1
      speed: 0.00
      sound: ENTITY_EXPERIENCE_ORB_PICKUP
      volume: 0.6
      pitch: 1.5
    take:
      particle: CLOUD
      count: 10
      offset: 1
      speed: 0.00
      sound: UI_BUTTON_CLICK
      volume: 0.5
      pitch: 1.8

  core:
    material: iadeco:small_fountain        # se quiser IA, troque por "meupack:core_furniture"
    # custom_block: ''                 # deixe vazio/comentado se usar IA no material

  altar:
    material: iadeco:table            # IA (namespace:id). Se for vanilla, use nome de Material.
    # custom_block: ''                 # deixe vazio/comentado se usar IA no material

    allowed_items:
      - BLAZE_ROD
      - DIAMOND

    allowed_custom:
      - mypack:magic_gem
      - runes:fire_core

    stand:
      small: true
      marker: true
      y_offset: 0.30
      radial_back_offset: 0.00
      spin:
        enabled: true
        deg_per_step: 2.0
        period_ticks: 1
        mode: HEAD_POSE

  area:
    size:
      width: 7
      length: 7
      height: 1

  altars:
    - "VVVPVVV"
    - "VPVVVPV"
    - "VVVVVVV"
    - "PVVAVVP"
    - "VVVVVVV"
    - "VPVVVPV"
    - "VVVPVVV"